name: kids_bible_app
description: An interactive Bible learning app for kids.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/noah_ark.png

fonts:
  - family: Fredoka
    fonts:
      - asset: assets/fonts/Fredoka-Regular.ttf

